language: objective-c
osx_image: xcode9.4
xcode_workspace: Example/SwiftyComments.xcworkspace
xcode_scheme: SwiftyComments-Example
#xcode_sdk: iphonesimulator9.3
podfile: Example/Podfile
#script:
#  - xcodebuild -project 'Example/SwiftyComments.xcodeproj' -scheme 'SwiftyComments-Example' -sdk iphonesimulator build
#cache:
#  directories:    
#    - Pods    
#    - $HOME/.cocoapods    
#    - $HOME/Library/Caches/CocoaPods